### PR TITLE
Get SwiftInspector working with Xcode 12.5

### PR DESCRIPTION
**Pull request by dfed**
Once this merges I'll release version `0.11.0`

Edit: OP said next release was `0.10.0` because I hadn't pulled latest `main` down!

### CODE REVIEW

**Review by fdiaz — APPROVED** [review]

**Comment by fdiaz** [comment]
JFYI it should be 0.11.0 😉

**Comment by fdiaz** [comment]
Let's also update the README 🙏

**Comment by dfed** [comment]
Done @fdiaz 4dbd40bf0ddaa18fe3f637b23458287a3b777907

**Comment by fdiaz** [comment]
@dfed let's update [this line](https://github.com/fdiaz/SwiftInspector/pull/94/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR1) and then we're good to go

**Comment by dfed** [comment]
Looks like [Github Actions won't have Xcode 12.5 available until June at the earliest](https://github.com/actions/virtual-environments/issues/2486#issuecomment-823881457). Going to merge this PR into a `develop-xcode-12-5` branch that'll have CI failing for now.

I ran `make develop` locally. I ran tests locally. They passed.

**Comment by fdiaz** [comment]
@dfed PTAL!

**Review by dfed — COMMENTED** [review]
Looks good @fdiaz

**Pull request merged**
