### PR TITLE
Use exact tag for Swift 5.5

### PR DESCRIPTION
**Pull request by dfed**
It's out! Let's use it.

### CODE REVIEW

**Comment by bachand** [comment]
Do we do the special packaging that allows this project to work across Xcode versions at this layer or a layer above? I am asking because I want to learn if changing the version requires any update to our packaging. I forget the exact name for what we do so hopefully that makes sense.

**Review by bachand — APPROVED** [review]

**Comment by bachand** [comment]
Or maybe we only updating the packaging for Xcode versions?

**Comment by fdiaz** [comment]
> Do we do the special packaging that allows this project to work across Xcode versions at this layer or a layer above? 

I'm not entirely sure what you mean by packaging. If you're talking about creating the binary, that's already independent of Xcode version and was done here https://github.com/fdiaz/SwiftInspector/pull/85

If you're referring to the fact that we can open SwiftInspector with versions of Xcode that contain different Swift versions, then this PR is the one that did it https://github.com/fdiaz/SwiftInspector/pull/108

The current PR is only updating what we did on https://github.com/fdiaz/SwiftInspector/pull/108 to now use the release version of SwiftSyntax instead of a branch.

**Comment by bachand** [comment]
I was referring to https://github.com/fdiaz/SwiftInspector/pull/85. Thank you!

**Pull request merged**
